export enum AuthError {
  MISSING_API_KEY = "MISSING_API_KEY",
  INVALID_API_KEY = "INVALID_API_KEY",
  KEY_NOT_KEYLESS_ELIGIBLE = "KEY_NOT_KEYLESS_ELIGIBLE",
  INTEROP_FORBIDDEN = "INTEROP_FORBIDDEN",
  TEAM_SUSPENDED = "TEAM_SUSPENDED",
  BACKEND_UNAVAILABLE = "AUTH_BACKEND_UNAVAILABLE",
  OAUTH_TOKEN_EXPIRED = "OAUTH_TOKEN_EXPIRED",
}

export enum BillingError {
  INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS",
  UNVERIFIED_CREDIT_LIMIT = "UNVERIFIED_CREDIT_LIMIT",
  SPONSOR_VERIFICATION_EXPIRED = "SPONSOR_VERIFICATION_EXPIRED",
  UNAVAILABLE = "BILLING_UNAVAILABLE",
}

export enum RateError {
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  QUEUE_FULL = "QUEUE_FULL",
}

export enum GatingError {
  URL_BLOCKED = "URL_BLOCKED",
  COUNTRY_RESTRICTED = "COUNTRY_RESTRICTED",
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",
}

export enum LifecycleError {
  JOB_NOT_FOUND = "JOB_NOT_FOUND",
  JOB_EXPIRED = "JOB_EXPIRED",
  JOB_WRONG_TEAM = "JOB_WRONG_TEAM",
  JOB_CANCELLED = "JOB_CANCELLED",
  ZDR_NOT_SUPPORTED = "ZDR_NOT_SUPPORTED",
}

export enum CrawlError {
  DENIAL = "CRAWL_DENIAL",
}

export enum ScrapeError {
  TIMEOUT = "SCRAPE_TIMEOUT",
  ALL_ENGINES_FAILED = "SCRAPE_ALL_ENGINES_FAILED",
  SSL = "SCRAPE_SSL_ERROR",
  SITE = "SCRAPE_SITE_ERROR",
  PROXY_SELECTION = "SCRAPE_PROXY_SELECTION_ERROR",
  PDF_PREFETCH_FAILED = "SCRAPE_PDF_PREFETCH_FAILED",
  DOCUMENT_PREFETCH_FAILED = "SCRAPE_DOCUMENT_PREFETCH_FAILED",
  JOB_CANCELLED = "SCRAPE_JOB_CANCELLED",
  RETRY_LIMIT = "SCRAPE_RETRY_LIMIT",
  ZDR_VIOLATION = "SCRAPE_ZDR_VIOLATION_ERROR",
  DNS = "SCRAPE_DNS_RESOLUTION_ERROR",
  PDF_INSUFFICIENT_TIME = "SCRAPE_PDF_INSUFFICIENT_TIME_ERROR",
  PDF_ANTIBOT = "SCRAPE_PDF_ANTIBOT_ERROR",
  PDF_OCR_REQUIRED = "SCRAPE_PDF_OCR_REQUIRED",
  DOCUMENT_ANTIBOT = "SCRAPE_DOCUMENT_ANTIBOT_ERROR",
  UNSUPPORTED_FILE = "SCRAPE_UNSUPPORTED_FILE_ERROR",
  ACTION = "SCRAPE_ACTION_ERROR",
  RACED_REDIRECT = "SCRAPE_RACED_REDIRECT_ERROR",
  NO_CACHED_DATA = "SCRAPE_NO_CACHED_DATA",
  LOCKDOWN_CACHE_MISS = "SCRAPE_LOCKDOWN_CACHE_MISS",
  SITEMAP = "SCRAPE_SITEMAP_ERROR",
  ACTIONS_NOT_SUPPORTED = "SCRAPE_ACTIONS_NOT_SUPPORTED",
  BRANDING_NOT_SUPPORTED = "SCRAPE_BRANDING_NOT_SUPPORTED",
  AUDIO_UNSUPPORTED_URL = "SCRAPE_AUDIO_UNSUPPORTED_URL",
  VIDEO_UNSUPPORTED_URL = "SCRAPE_VIDEO_UNSUPPORTED_URL",
  X_TWITTER_CONFIGURATION = "SCRAPE_X_TWITTER_CONFIGURATION_ERROR",
}

export enum ExtractError {
  NO_VALID_URLS = "EXTRACT_NO_VALID_URLS",
  SCHEMA_MISMATCH = "EXTRACT_SCHEMA_MISMATCH",
  LLM_REFUSAL = "EXTRACT_LLM_REFUSAL",
  SCRAPE_FAILED = "EXTRACT_SCRAPE_FAILED",
}

export enum AgentError {
  INDEX_ONLY = "AGENT_INDEX_ONLY",
  UPSTREAM = "AGENT_UPSTREAM_ERROR",
}

export enum MapError {
  TIMEOUT = "MAP_TIMEOUT",
  FAILED = "MAP_FAILED",
}

export enum DependencyError {
  UNAVAILABLE = "DEPENDENCY_UNAVAILABLE",
  TIMEOUT = "DEPENDENCY_TIMEOUT",
}

export enum BrowserError {
  SESSION_NOT_FOUND = "BROWSER_SESSION_NOT_FOUND",
  SESSION_EXPIRED = "BROWSER_SESSION_EXPIRED",
  SESSION_FORBIDDEN = "BROWSER_SESSION_FORBIDDEN",
  SESSION_LIMIT_EXCEEDED = "BROWSER_SESSION_LIMIT_EXCEEDED",
  EXECUTION_FAILED = "BROWSER_EXECUTION_FAILED",
  SERVICE_UNAVAILABLE = "BROWSER_SERVICE_UNAVAILABLE",
}

export enum MonitorError {
  MONITOR_NOT_FOUND = "MONITOR_NOT_FOUND",
  CHECK_NOT_FOUND = "MONITOR_CHECK_NOT_FOUND",
  EMAIL_TOKEN_INVALID = "MONITOR_EMAIL_TOKEN_INVALID",
  EMAIL_TOKEN_EXPIRED = "MONITOR_EMAIL_TOKEN_EXPIRED",
  CONFLICT = "MONITOR_CONFLICT",
}

export enum ProxyError {
  UPSTREAM_UNAVAILABLE = "PROXY_UPSTREAM_UNAVAILABLE",
  UPSTREAM_TIMEOUT = "PROXY_UPSTREAM_TIMEOUT",
  UPSTREAM_BAD_RESPONSE = "PROXY_UPSTREAM_BAD_RESPONSE",
  NOT_CONFIGURED = "PROXY_NOT_CONFIGURED",
}

export enum FeedbackError {
  TARGET_NOT_FOUND = "FEEDBACK_TARGET_NOT_FOUND",
  WINDOW_EXPIRED = "FEEDBACK_WINDOW_EXPIRED",
  TEAM_OPTED_OUT = "FEEDBACK_TEAM_OPTED_OUT",
  DB_UNAVAILABLE = "FEEDBACK_DB_UNAVAILABLE",
  PREVIEW_UNAVAILABLE = "FEEDBACK_PREVIEW_UNAVAILABLE",
  JOB_NOT_SUCCESSFUL = "FEEDBACK_JOB_NOT_SUCCESSFUL",
}

export enum LocalError {
  FEATURE_UNSUPPORTED = "FEATURE_UNSUPPORTED_LOCALLY",
}

export enum RequestError {
  BAD_REQUEST = "BAD_REQUEST",
  BAD_REQUEST_INVALID_JSON = "BAD_REQUEST_INVALID_JSON",
  PARSE_UNSUPPORTED_OPTIONS = "PARSE_UNSUPPORTED_OPTIONS",
}

export enum CommonError {
  UNKNOWN = "UNKNOWN_ERROR",
}

export type ErrorCodes =
  | AuthError
  | BillingError
  | RateError
  | GatingError
  | LifecycleError
  | CrawlError
  | ScrapeError
  | ExtractError
  | AgentError
  | MapError
  | DependencyError
  | BrowserError
  | MonitorError
  | ProxyError
  | FeedbackError
  | LocalError
  | RequestError
  | CommonError;

export enum ScrapeWarning {
  ENGINE_PARTIAL_FEATURES = "SCRAPE_ENGINE_PARTIAL_FEATURES",
}

export enum LiveWarning {
  CAPTURE_UNAVAILABLE = "LIVE_CAPTURE_UNAVAILABLE",
  RECORDING_FAILED = "LIVE_RECORDING_FAILED",
  SCREENSHOT_FAILED = "LIVE_SCREENSHOT_FAILED",
  WS_PROXY_FAILED = "LIVE_WS_PROXY_FAILED",
}

export enum ExtractWarning {
  CONTENT_TRIMMED_CHARS = "EXTRACT_CONTENT_TRIMMED_CHARS",
  CONTENT_TRIMMED_TOKENS = "EXTRACT_CONTENT_TRIMMED_TOKENS",
  TOKEN_COUNT_FAILED = "EXTRACT_TOKEN_COUNT_FAILED",
  CLEANING_SKIPPED_TOO_LONG = "EXTRACT_CLEANING_SKIPPED_TOO_LONG",
}

export enum QueryWarning {
  ZDR_UNSUPPORTED = "QUERY_ZDR_UNSUPPORTED",
  NO_MARKDOWN = "QUERY_NO_MARKDOWN",
  EMPTY_MARKDOWN = "QUERY_EMPTY_MARKDOWN",
  GENERATION_FAILED = "QUERY_GENERATION_FAILED",
  HIGHLIGHTS_FAILED = "QUERY_HIGHLIGHTS_FAILED",
}

export enum ChangeTrackingWarning {
  ZDR_UNSUPPORTED = "CHANGE_TRACKING_ZDR_UNSUPPORTED",
  COMPARE_FAILED = "CHANGE_TRACKING_COMPARE_FAILED",
  STRUCTURED_DIFF_FAILED = "CHANGE_TRACKING_STRUCTURED_DIFF_FAILED",
}

export enum MediaWarning {
  AUDIO_UNAVAILABLE = "MEDIA_AUDIO_UNAVAILABLE",
  VIDEO_UNAVAILABLE = "MEDIA_VIDEO_UNAVAILABLE",
}

export enum MapWarning {
  NO_RESULTS = "MAP_NO_RESULTS",
  SITEMAP_FAILED = "MAP_SITEMAP_FAILED",
}

export enum CrawlWarning {
  FEW_RESULTS = "CRAWL_FEW_RESULTS",
}

export type WarningCodes =
  | ScrapeWarning
  | LiveWarning
  | ExtractWarning
  | QueryWarning
  | ChangeTrackingWarning
  | MediaWarning
  | MapWarning
  | CrawlWarning;
