CREATE TABLE "agent_sponsors" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_sponsors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"verification_deadline" timestamp with time zone NOT NULL,
	"agent_name" text NOT NULL,
	"sandboxed_team_id" uuid,
	"api_key_id" bigint,
	"requesting_ip" text,
	"tos_version" text,
	"tos_hash" text,
	"verification_token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"verified_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "agents" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"cost_tracking" jsonb,
	"is_successful" boolean NOT NULL,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "api_keys" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "api_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now(),
	"key" uuid DEFAULT gen_random_uuid(),
	"name" text,
	"team_id" uuid,
	"owner_id" uuid,
	"agent_provisioned" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "batch_scrapes" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"num_docs" integer NOT NULL,
	"credits_cost" integer NOT NULL,
	"cancelled" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blocklist" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "blocklist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"data" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blocklist_hits" (
	"id" uuid NOT NULL,
	"domain" text NOT NULL,
	"url" text,
	"team_id" uuid,
	"origin" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "browser_session_activities" (
	"id" bigint GENERATED ALWAYS AS IDENTITY (sequence name "browser_session_activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"team_id" text NOT NULL,
	"session_id" text NOT NULL,
	"language" text NOT NULL,
	"timeout" integer NOT NULL,
	"exit_code" integer,
	"killed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"source" text DEFAULT 'browser'
);
--> statement-breakpoint
CREATE TABLE "browser_sessions" (
	"id" uuid NOT NULL,
	"team_id" text NOT NULL,
	"browser_id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"context_id" text NOT NULL,
	"cdp_url" text NOT NULL,
	"cdp_path" text NOT NULL,
	"stream_web_view" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"ttl_total" integer NOT NULL,
	"ttl_without_activity" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"credits_used" integer,
	"cdp_interactive_path" text,
	"scrape_id" uuid
);
--> statement-breakpoint
CREATE TABLE "concurrency_log" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "concurrency_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"team_id" uuid NOT NULL,
	"concurrency" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "crawls" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"url" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"num_docs" integer NOT NULL,
	"credits_cost" integer NOT NULL,
	"cancelled" boolean NOT NULL,
	"monitor_id" uuid,
	"monitor_check_id" uuid
);
--> statement-breakpoint
CREATE TABLE "deep_researches" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"query" text NOT NULL,
	"team_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"cost_tracking" jsonb,
	"options" jsonb
);
--> statement-breakpoint
CREATE TABLE "deterministic_json_llm_cache" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"cache_key" text NOT NULL UNIQUE,
	"response" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deterministic_json_scripts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"cache_key" text NOT NULL UNIQUE,
	"code" text NOT NULL,
	"url" text,
	"model" text,
	"cache_version" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "eb-sync" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "eb-sync_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"team_id" text
);
--> statement-breakpoint
CREATE TABLE "extracts" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"urls" text[] NOT NULL,
	"options" jsonb,
	"model_kind" text NOT NULL,
	"team_id" uuid NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"credits_cost" integer NOT NULL,
	"cost_tracking" jsonb
);
--> statement-breakpoint
CREATE TABLE "idempotency_keys" (
	"key" uuid DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "keyless_credit_usage" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "keyless_credit_usage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"team_id" uuid NOT NULL,
	"ip" text NOT NULL,
	"credits_used" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "llm_texts" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"origin_url" text NOT NULL,
	"llmstxt" text NOT NULL,
	"llmstxt_full" text NOT NULL,
	"max_urls" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "llmstxts" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"url" text NOT NULL,
	"team_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"num_urls" integer NOT NULL,
	"options" jsonb,
	"cost_tracking" jsonb,
	"credits_cost" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maps" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"url" text NOT NULL,
	"options" jsonb,
	"team_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"num_results" integer NOT NULL,
	"credits_cost" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitor_check_pages" (
	"id" uuid NOT NULL,
	"check_id" uuid NOT NULL,
	"monitor_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"target_id" text NOT NULL,
	"url" text NOT NULL,
	"url_hash" bytea NOT NULL,
	"status" text NOT NULL,
	"previous_scrape_id" uuid,
	"current_scrape_id" uuid,
	"diff_gcs_key" text,
	"diff_text_bytes" integer,
	"diff_json_bytes" integer,
	"status_code" integer,
	"error" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"judgment" jsonb
);
--> statement-breakpoint
CREATE TABLE "monitor_checks" (
	"id" uuid NOT NULL,
	"monitor_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"trigger" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"scheduled_for" timestamp with time zone,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"estimated_credits" integer,
	"reserved_credits" integer,
	"actual_credits" integer,
	"autumn_lock_id" text,
	"billing_status" text DEFAULT 'not_applicable' NOT NULL,
	"total_pages" integer DEFAULT 0 NOT NULL,
	"same_count" integer DEFAULT 0 NOT NULL,
	"changed_count" integer DEFAULT 0 NOT NULL,
	"new_count" integer DEFAULT 0 NOT NULL,
	"removed_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"target_results" jsonb,
	"webhook_payload" jsonb,
	"email_payload" jsonb,
	"notification_status" jsonb,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitor_email_recipients" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"monitor_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"email" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"token" text NOT NULL,
	"source" text DEFAULT 'opt_in' NOT NULL,
	"confirmation_sent_at" timestamp with time zone,
	"confirmed_at" timestamp with time zone,
	"unsubscribed_at" timestamp with time zone,
	"last_notified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitor_pages" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"monitor_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"target_id" text NOT NULL,
	"url" text NOT NULL,
	"url_hash" bytea NOT NULL,
	"source" text NOT NULL,
	"first_seen_check_id" uuid,
	"last_seen_check_id" uuid,
	"last_changed_check_id" uuid,
	"last_scrape_id" uuid,
	"last_status" text NOT NULL,
	"is_removed" boolean DEFAULT false NOT NULL,
	"removed_at" timestamp with time zone,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitors" (
	"id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"name" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"schedule_cron" text NOT NULL,
	"schedule_timezone" text DEFAULT 'UTC' NOT NULL,
	"next_run_at" timestamp with time zone,
	"last_run_at" timestamp with time zone,
	"last_check_id" uuid,
	"current_check_id" uuid,
	"locked_at" timestamp with time zone,
	"locked_until" timestamp with time zone,
	"retention_days" integer DEFAULT 30 NOT NULL,
	"estimated_credits_per_month" integer,
	"targets" jsonb DEFAULT '[]' NOT NULL,
	"webhook" jsonb,
	"notification" jsonb,
	"last_check_summary" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"goal" text,
	"judge_enabled" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"last_referral_notification" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email_preferences" text[] DEFAULT '{rate_limit_warnings,system_alerts}'::text[],
	"unsubscribed_all" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "parses" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"url" text NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"time_taken" numeric NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"cost_tracking" jsonb,
	"pdf_num_pages" integer,
	"credits_cost" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prices" (
	"id" text NOT NULL,
	"product_id" text,
	"active" boolean DEFAULT true NOT NULL,
	"description" text,
	"unit_amount" bigint,
	"currency" text DEFAULT 'usd',
	"type" text DEFAULT 'recurring',
	"interval" text,
	"interval_count" integer DEFAULT 1,
	"trial_period_days" integer DEFAULT 0,
	"metadata" jsonb DEFAULT '{}',
	"credits" integer DEFAULT 50,
	"is_usage" boolean DEFAULT false,
	"rate_limits" jsonb,
	"concurrency" integer,
	"plan_priority" jsonb,
	"upfront" boolean DEFAULT false,
	"slug" text DEFAULT gen_random_uuid() NOT NULL,
	"should_be_graceful" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"unit_amount_rollover_cap" smallint DEFAULT 0 NOT NULL,
	"associated_auto_recharge_price_id" text,
	"exp_pack_max_per_month" integer
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"name" text,
	"description" text,
	"image" text,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"order" smallint,
	"test_mode" boolean DEFAULT true,
	"is_enterprise" boolean DEFAULT false,
	"is_extract" boolean DEFAULT false,
	"is_displayed" boolean DEFAULT false,
	"is_stripe_test" boolean DEFAULT false,
	"slug" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" text
);
--> statement-breakpoint
CREATE TABLE "requests" (
	"id" uuid NOT NULL,
	"kind" text NOT NULL,
	"api_version" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"team_id" uuid NOT NULL,
	"origin" text NOT NULL,
	"integration" text,
	"target_hint" text NOT NULL,
	"dr_clean_by" timestamp with time zone,
	"api_key_id" bigint
);
--> statement-breakpoint
CREATE TABLE "research_github_searches" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"target" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"response" jsonb,
	"num_results" integer NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "research_paper_inspects" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"target" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"response" jsonb,
	"num_results" integer NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "research_paper_reads" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"target" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"response" jsonb,
	"num_results" integer NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "research_paper_searches" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"target" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"response" jsonb,
	"num_results" integer NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "research_related_papers" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"target" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"response" jsonb,
	"num_results" integer NOT NULL,
	"time_taken" numeric NOT NULL,
	"credits_cost" integer NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scrapes" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"url" text NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"time_taken" numeric NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"cost_tracking" jsonb,
	"pdf_num_pages" integer,
	"credits_cost" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"monitor_id" uuid,
	"monitor_check_id" uuid,
	"content_type" text
);
--> statement-breakpoint
CREATE TABLE "search_feedback" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"search_id" uuid,
	"endpoint" text DEFAULT 'search' NOT NULL,
	"job_id" uuid,
	"request_id" uuid,
	"api_version" text DEFAULT 'v2',
	"team_id" uuid NOT NULL,
	"api_key_id" bigint,
	"overall_rating" text NOT NULL,
	"issue_types" text[] DEFAULT '{}'::text[] NOT NULL,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"comment" text,
	"valuable_sources" jsonb DEFAULT '[]' NOT NULL,
	"missing_content" jsonb DEFAULT '[]' NOT NULL,
	"query_suggestions" text,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"job_status" text,
	"credits_billed" integer DEFAULT 0 NOT NULL,
	"integration" text,
	"origin" text,
	"credits_refunded" integer DEFAULT 0 NOT NULL,
	"refund_policy" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "searches" (
	"id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"query" text NOT NULL,
	"team_id" uuid NOT NULL,
	"options" jsonb,
	"time_taken" numeric NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"credits_cost" integer NOT NULL,
	"is_successful" boolean NOT NULL,
	"error" text,
	"num_results" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" text NOT NULL,
	"user_id" uuid NOT NULL,
	"status" text,
	"metadata" jsonb,
	"price_id" text,
	"quantity" integer,
	"cancel_at_period_end" boolean,
	"created" timestamp with time zone DEFAULT now() NOT NULL,
	"current_period_start" timestamp with time zone DEFAULT now() NOT NULL,
	"current_period_end" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone DEFAULT now(),
	"cancel_at" timestamp with time zone DEFAULT now(),
	"canceled_at" timestamp with time zone DEFAULT now(),
	"trial_start" timestamp with time zone DEFAULT now(),
	"trial_end" timestamp with time zone DEFAULT now(),
	"team_id" uuid,
	"is_usage" boolean DEFAULT false,
	"is_extract" boolean DEFAULT false,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expansion_associated_coupon" bigint,
	"pending_price_id" text,
	"pending_price_effective_at" timestamp with time zone,
	"pending_schedule_id" text
);
--> statement-breakpoint
CREATE TABLE "teams" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"name" text,
	"banned" boolean DEFAULT false,
	"idmux_expires_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now(),
	"hmac_secret" text DEFAULT encode(gen_random_bytes(32), 'hex'::text) NOT NULL,
	"referrer_integration" varchar,
	"allocated_concurrent_browsers" integer,
	"org_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_notifications" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"team_id" uuid,
	"notification_type" text NOT NULL,
	"sent_date" date NOT NULL,
	"email_id" text,
	"timestamp" timestamp with time zone,
	"read" boolean DEFAULT false,
	"metadata" jsonb
);
--> statement-breakpoint
CREATE TABLE "user_teams" (
	"user_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"role" text DEFAULT 'admin',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid NOT NULL,
	"full_name" text,
	"avatar_url" text,
	"billing_address" jsonb,
	"payment_method" jsonb,
	"email" text,
	"team_id" uuid,
	"created_on" timestamp with time zone DEFAULT now(),
	"referrer_integration" varchar
);
--> statement-breakpoint
CREATE TABLE "webhook_logs" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"success" boolean NOT NULL,
	"error" text,
	"team_id" uuid NOT NULL,
	"crawl_id" uuid NOT NULL,
	"scrape_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"url" text NOT NULL,
	"status_code" smallint,
	"event" text NOT NULL,
	"latency_ms" integer DEFAULT 0
);
