-- Local development stubs: Supabase RPCs + index-db tables that don't exist locally.
-- Run once after applying the drizzle migration:
--   psql $DATABASE_URL -f apps/api/scripts/local-db-setup.sql
--
-- Test API key: fc-3d478a296e59403e85c794aba81ffd2a
-- This is a dummy local key. It parses to a UUID-shaped value so the auth
-- middleware accepts it, but it is not a real credential.

-- ---------------------------------------------------------------------------
-- Index-DB tables (index-db.ts schema — separate Supabase project in prod,
-- shared with the main DB locally via INDEX_DATABASE_URL=DATABASE_URL).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "index" (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  url text NOT NULL,
  url_hash bytea NOT NULL,
  original_url text NOT NULL,
  resolved_url text NOT NULL,
  has_screenshot boolean NOT NULL,
  has_screenshot_fullscreen boolean NOT NULL,
  is_mobile boolean NOT NULL,
  block_ads boolean NOT NULL,
  location_country text,
  location_languages text[],
  status integer NOT NULL,
  title text,
  description text,
  invalidated_at timestamptz,
  is_precrawl boolean,
  wait_time_ms bigint,
  is_stealth boolean NOT NULL DEFAULT false,
  url_split_0_hash bytea NOT NULL,
  url_split_1_hash bytea,
  url_split_2_hash bytea,
  url_split_3_hash bytea,
  url_split_4_hash bytea,
  url_split_5_hash bytea,
  url_split_6_hash bytea,
  url_split_7_hash bytea,
  url_split_8_hash bytea,
  url_split_9_hash bytea,
  domain_splits_0_hash bytea,
  domain_splits_1_hash bytea,
  domain_splits_2_hash bytea,
  domain_splits_3_hash bytea,
  domain_splits_4_hash bytea
);

CREATE TABLE IF NOT EXISTS engpicker_queue (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  domain_hash bytea NOT NULL,
  domain_level integer NOT NULL,
  picked_up_at timestamptz,
  done boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS engpicker_verdicts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  domain_hash bytea NOT NULL,
  verdict varchar NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- auth_credit_usage_chunk_47
-- Accepts any API key, returns a bypass ACUC row with 99 999 999 credits.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION auth_credit_usage_chunk_47(
  input_key text,
  i_is_extract boolean DEFAULT false,
  tally_untallied_credits boolean DEFAULT false
) RETURNS TABLE (
  api_key                                    text,
  api_key_id                                 bigint,
  team_id                                    uuid,
  sub_id                                     text,
  sub_current_period_start                   timestamptz,
  sub_current_period_end                     timestamptz,
  sub_user_id                                text,
  price_id                                   text,
  rate_limits                                jsonb,
  price_credits                              numeric,
  price_should_be_graceful                   boolean,
  price_associated_auto_recharge_price_id    text,
  credits_used                               numeric,
  coupon_credits                             numeric,
  adjusted_credits_used                      numeric,
  remaining_credits                          numeric,
  total_credits_sum                          numeric,
  plan_priority                              jsonb,
  concurrency                                integer,
  flags                                      jsonb,
  is_extract                                 boolean,
  org_id                                     uuid
) LANGUAGE sql AS $$
  SELECT
    input_key::text,
    0::bigint,
    '00000000-0000-0000-0000-000000000001'::uuid,
    'local-sub',
    now() - interval '30 days',
    now() + interval '30 days',
    'local-user',
    'local-price',
    '{"crawl":99999999,"scrape":99999999,"extract":99999999,"search":99999999,"map":99999999,"preview":99999999,"crawlStatus":99999999,"extractStatus":99999999}'::jsonb,
    99999999::numeric,
    false,
    null::text,
    0::numeric,
    99999999::numeric,
    0::numeric,
    99999999::numeric,
    99999999::numeric,
    '{"bucketLimit":25,"planModifier":1}'::jsonb,
    100::integer,
    null::jsonb,
    i_is_extract,
    null::uuid
$$;

-- ---------------------------------------------------------------------------
-- auth_credit_usage_chunk_47_from_team
-- Same as above but keyed by team_id instead of API key.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION auth_credit_usage_chunk_47_from_team(
  input_team uuid,
  i_is_extract boolean DEFAULT false,
  tally_untallied_credits boolean DEFAULT false
) RETURNS TABLE (
  api_key                                    text,
  api_key_id                                 bigint,
  team_id                                    uuid,
  sub_id                                     text,
  sub_current_period_start                   timestamptz,
  sub_current_period_end                     timestamptz,
  sub_user_id                                text,
  price_id                                   text,
  rate_limits                                jsonb,
  price_credits                              numeric,
  price_should_be_graceful                   boolean,
  price_associated_auto_recharge_price_id    text,
  credits_used                               numeric,
  coupon_credits                             numeric,
  adjusted_credits_used                      numeric,
  remaining_credits                          numeric,
  total_credits_sum                          numeric,
  plan_priority                              jsonb,
  concurrency                                integer,
  flags                                      jsonb,
  is_extract                                 boolean,
  org_id                                     uuid
) LANGUAGE sql AS $$
  SELECT
    'local-key'::text,
    0::bigint,
    input_team,
    'local-sub',
    now() - interval '30 days',
    now() + interval '30 days',
    'local-user',
    'local-price',
    '{"crawl":99999999,"scrape":99999999,"extract":99999999,"search":99999999,"map":99999999,"preview":99999999,"crawlStatus":99999999,"extractStatus":99999999}'::jsonb,
    99999999::numeric,
    false,
    null::text,
    0::numeric,
    99999999::numeric,
    0::numeric,
    99999999::numeric,
    99999999::numeric,
    '{"bucketLimit":25,"planModifier":1}'::jsonb,
    100::integer,
    null::jsonb,
    i_is_extract,
    null::uuid
$$;

-- ---------------------------------------------------------------------------
-- bill_team_6
-- No-op billing stub — local dev doesn't deduct credits.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION bill_team_6(
  _team_id uuid,
  credits numeric,
  sub_id text DEFAULT null,
  fetch_subscription boolean DEFAULT false,
  i_api_key_id bigint DEFAULT null,
  is_extract_param boolean DEFAULT false
) RETURNS TABLE (api_key text) LANGUAGE sql AS $$
  SELECT 'local-key'::text;
$$;

-- ---------------------------------------------------------------------------
-- insert_omce_job_if_needed
-- No-op OMCE stub — local dev doesn't enqueue index jobs in Supabase.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION insert_omce_job_if_needed(
  i_domain_level integer,
  i_domain_hash bytea
) RETURNS void LANGUAGE sql AS $$
  -- no-op
$$;

-- ---------------------------------------------------------------------------
-- change_tracking_insert_scrape
-- No-op change-tracking stub — no Supabase realtime needed locally.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION change_tracking_insert_scrape(
  p_team_id uuid,
  p_url text,
  p_job_id uuid,
  p_date_added timestamptz,
  p_change_tracking_tag text DEFAULT null
) RETURNS void LANGUAGE sql AS $$
  -- no-op
$$;
